<?php
 Route::group(['namespace'=>'Parents'],function(){            
     Route::get('/parents','ParentController@index')->name('parents.index');
     Route::get('/parents/create','ParentController@create')->name('parents.create');
     Route::post('/parents/store','ParentController@store')->name('parents.store');
     Route::post('/parents/destroy','ParentController@destroy')->name('parents.destroy');
     Route::get('/parents/fathers/show/{id}/{fatherName}','ParentController@fatherShow')->name('father.show');
     Route::get('/parents/fathers/{id}/edit','ParentController@editFather')->name('fathers.edit');
     Route::post('/parents/fathers/update/{id}','ParentController@updateFather')->name('fathers.update');
     Route::get('/parents/fathers/add-wife/{id}','ParentController@addWife')->name('fathers.addWife');
     Route::post('/parents/fathers/add-wife','ParentController@storeWife')->name('addWife.store');
     Route::get('/parents/mothers/show/{id}/{motherName}','ParentController@motherShow')->name('mother.show');
});