<?php
 Route::group(['namespace'=>'Parents'],function(){            
     Route::get('/parents','ParentController@index')->name('parents.index');
     Route::get('/parents/{id}/edit','ParentController@edit')->name('parents.edit');
     Route::get('/parents/create','ParentController@create')->name('parents.create');
     Route::post('/parents/store','ParentController@store')->name('parents.store');
     Route::post('/parents/destroy','ParentController@destroy')->name('parents.destroy');
     Route::get('/parents/fathers/show/{id}','ParentController@fatherShow')->name('father.show');
     Route::get('/parents/mothers/show/{id}','ParentController@motherShow')->name('mother.show');
});